### PR TITLE
CP-23007: Add support for add-fd and remove-fd QMP message

### PR DESCRIPTION
**Pull request by fillzero**
Signed-off-by: Liang Dai <liang.dai1@citrix.com>

### CODE REVIEW

**Comment by lindig** [comment]
I'm not happy with the current handling of JSON in ocaml-qmp and have suggested a better approach to @mg12 in CA-261854. I am not going to accept any additions before this is done.

**Comment by lindig** [comment]
Please open this PR again after the JSON handling has been simplified in CA-261854.

**Comment by lindig** [comment]
The JSON handling has been improved - so we can now add the support for `{add,remove}-fd`. You can re-open the PR.

**Comment by fillzero** [comment]
Thanks, reopen this PR.

**Pull request closed without merging**
